name: Extract YouTube Stream URL

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'YouTube URL'
        required: true

jobs:
  extract-stream:
    runs-on: ubuntu-latest

    steps:
      - name: Install yt-dlp
        run: |
          python3 -m pip install --upgrade pip
          pip install yt-dlp

      - name: Save YouTube cookies file
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Extract streaming URL using yt-dlp and cookies
        id: extract
        run: |
          echo "📺 Extracting: ${{ github.event.inputs.youtube_url }}"
          stream_url=$(yt-dlp --cookies cookies.txt -g "${{ github.event.inputs.youtube_url }}")
          echo "STREAM_URL=$stream_url" >> $GITHUB_ENV
          echo "::set-output name=stream_url::$stream_url"
          echo "✅ Stream URL extracted"

      - name: Save streaming URL to Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Must be PAT with 'gist' scope
          STREAM_URL: ${{ env.STREAM_URL }}
        run: |
          curl -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"description\": \"YouTube Stream URL\",\"public\": true,\"files\": {\"stream_url.txt\": {\"content\": \"$STREAM_URL\"}}}" \
            https://api.github.com/gists
