name: Extract YouTube Stream URL

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'YouTube URL'
        required: true

jobs:
  extract-stream:
    runs-on: ubuntu-latest

    steps:
      - name: Install yt-dlp
        run: |
          python3 -m pip install --upgrade pip
          pip install yt-dlp

      - name: Extract streaming URL
        id: extract
        run: |
          echo "YouTube URL: ${{ github.event.inputs.youtube_url }}"
          stream_url=$(yt-dlp -g "${{ github.event.inputs.youtube_url }}")
          echo "STREAM_URL=$stream_url" >> $GITHUB_ENV
          echo "✅ Stream URL extracted: $stream_url"

      - name: Save to Gist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"description\": \"YouTube Stream URL\",\"public\": true,\"files\": {\"stream_url.txt\": {\"content\": \"${{ env.STREAM_URL }}\"}}}" \
            https://api.github.com/gists
